### Calc_Profile_retreat_rates

Load profiles extracted using Global Mapper and calculate volume changes for each profile

In [1]:
import numpy as np
#import rasterio
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

profile_dates = ([\
#         "22-Jan-2016",\ # Need dates at end of change
         "25-Jan-2016",\
         "11-Feb-2016",\
         "30-Mar-2016",\
         "21-Sep-2016",\
         "09-Jan-2017",\
         "25-Jan-2017",\
         "14-Feb-2017",\
         "16-Mar-2017",\
         "28-Apr-2017",\
         "04-May_2017",\
         "18-Sep-2017",\
#         "03-Jan-2017",\
         "10-Jan-2018",\
         "09-Mar-2018"]
         )
# the following names should be changed for each use
# specify the location and name of the DEM
#fdir = "F:\\2017_Karen_Sandwich_maps\\profiles\\"
fdir = "D:\\2017_Karen_Sandwich_maps\\profiles\\"

fnames = (["P1all.csv","P2all.csv","P3all.csv","P4all.csv","PAall.csv","PBall.csv","PCall.csv","P5all.csv","P6all.csv"])
#fnames = (["P1all.csv","P2all.csv","P3all.csv","P4all.csv","PAall.csv","PBall.csv","PCall.csv","P5all.csv","P6all.csv"])

dfr = pd.DataFrame(index=profile_dates,columns=fnames)


#df=pd.read_csv(fdir+fn,header = None, names = column_names)
for file in fnames:
    df=pd.read_csv(fdir+file,header = None,skiprows=1)
    # print("Read: ",len(df.index),' lines.')
    # print(df)
    pr = df.as_matrix((4,5,6,7,8,9,10,11,12,13,14,15,16,17))
    dx = df[18].values
    dxm = np.median(dx)
    dpr = np.diff(pr*dxm)
    dv = np.nansum(dpr)
    dpr[np.isnan(dpr)]=0.
    dv = np.sum(dpr, axis=(0))
    dfr[file]=dv

C:\Users\csherwood\AppData\Local\Continuum\Anaconda\envs\IOOS3\lib\site-packages\ipykernel\__main__.py:39: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

In [2]:
dfr

,P1all.csv,P2all.csv,P3all.csv,P4all.csv,PAall.csv,PBall.csv,PCall.csv,P5all.csv,P6all.csv
25-Jan-2016,-25.806088,-21.278659,-20.229837,-0.859680,3.106169,1.161976,-0.817438,-0.467196,4.027257
11-Feb-2016,-48.696905,-24.648279,-9.797212,-4.584553,-5.882103,-2.896514,-1.187479,-1.838774,-6.770267
30-Mar-2016,-5.116537,-6.277414,-17.256479,12.469103,8.765894,5.617445,4.805333,9.156470,-3.509759
21-Sep-2016,-9.341906,-7.017389,6.965451,2.393750,5.907777,1.614056,2.236825,-9.232247,-1.672828
09-Jan-2017,-10.529391,-16.718137,-13.878679,4.617102,7.386505,9.082166,8.156259,6.602299,20.115432
25-Jan-2017,-1.098799,1.243329,-10.998522,7.373358,-0.559291,0.497332,3.151300,-17.677477,-41.561225
14-Feb-2017,-16.437906,-17.094548,-15.471251,-5.849615,-3.502961,-7.264485,-13.476769,10.020232,6.723247
16-Mar-2017,-0.665132,2.380843,3.479849,9.500920,7.084306,8.488665,9.542091,1.693192,1.585733
28-Apr-2017,-2.593672,1.442379,2.872997,-6.000519,-3.719903,-12.147801,-7.662712,-9.451401,-12.222720
04-May_2017,-3.480867,-0.672636,-2.662145,-2.270161,-3.137536,-0.567003,-1.827819,4.083097,9.533251
18-Sep-2017,7.255385,-0.373613,-3.225635,-1.953401,2.081234,3.988594,3.212543,0.425168,2.595113
10-Jan-2018,-29.018937,-12.453913,-0.847532,7.965359,-2.095351,-3.104047,-5.678159,39.950114,-6.344025
09-Mar-2018,-33.825477,-76.386917,-61.649563,-14.933425,-54.896832,-76.062470,-93.599489,-45.541331,-99.127673

In [ ]:
dfr.to_csv('retreat_rates.csv')

In [4]:
dfr.describe()

,P1all.csv,P2all.csv,P3all.csv,P4all.csv,PAall.csv,PBall.csv,PCall.csv,P5all.csv,P6all.csv
count,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000
mean,-13.796633,-13.681150,-10.976812,0.605249,-3.035545,-5.507084,-7.165039,-0.944450,-9.740651
std,16.116113,20.990823,17.505587,7.690919,16.328907,22.015401,26.735426,19.141230,30.464413
min,-48.696905,-76.386917,-61.649563,-14.933425,-54.896832,-76.062470,-93.599489,-45.541331,-99.127673
25%,-25.806088,-17.094548,-15.471251,-4.584553,-3.502961,-3.104047,-5.678159,-9.232247,-6.770267
50%,-9.341906,-7.017389,-9.797212,-0.859680,-0.559291,0.497332,-0.817438,0.425168,-1.672828
75%,-2.593672,-0.373613,-0.847532,7.373358,5.907777,3.988594,3.212543,6.602299,4.027257
max,7.255385,2.380843,6.965451,12.469103,8.765894,9.082166,9.542091,39.950114,20.115432